services:

  db:
    container_name: db
    image: postgres:15
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - ${POSTGRES_PORT}
    command: -p ${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-p", "${POSTGRES_PORT}" ]
      start_period: 3s
      interval: 5s
      timeout: 5s
      retries: 5


  app:
    container_name: example_app
    build:
      context: .
    env_file: .env
    ports:
      - ${BACKEND_PORT}:8000
    environment:
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - temp_data:/app/temp

volumes:
  db_data:
  temp_data:
